name: Run NSAID Side Effects Script

on:
  push:
    branches:
      - main  # This will trigger the workflow when changes are pushed to the 'main' branch

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3  # Update to v3 to use a newer Node.js version
        
      - name: Set up Python
        uses: actions/setup-python@v4  # Update to v4 to use a newer Node.js version
        with:
          python-version: '3.x'  # Define Python version

      - name: Install requests library
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run Python script
        run: |
          python search_nsaid_side_effects.py
